### ISSUE TITLE
Where is my August 31?

### ISSUE THREAD

**Issue by gmoqa** [Paul-DS/bootstrap-year-calendar#179]
This may sound stupid, but for some reason I can not visualize on August 31, It does not appear in my project, it does not appear in the examples.

![image](https://user-images.githubusercontent.com/1767051/32605998-5531d586-c532-11e7-890d-25a3c5480de7.png)

**Comment by William-H-M** [comment]
If not wrong Chile has or is on DST right now (Yes, I stalked you...) that's why this happens it's being reported for all browser and it's a deal with how JavaScript and browsers deal with it, for you in this case doesn't appear for other is duplcated!, and quoted from [Matt Johnson](https://github.com/mj1856) of [Moment.js](http://momentjs.com/)

 >   To be clear, this is a browser issue - not a moment issue. Similar results can be obtained by just using the Date object. Moment could detect this issue and compensate, but it currently does not.

Source of quote
https://stackoverflow.com/questions/32573951/getting-invalid-day-in-date-when-using-moment-js-in-mozilla-firefox

**Comment by guquinteros** [comment]
Thanks for the info, now with this, I'll see how to solve it, it's so funny. 

![image](https://user-images.githubusercontent.com/1767051/32622806-e1f9ba4e-c562-11e7-88d2-a7f150eb2023.png)
