### ISSUE TITLE
ajax DataSource

### ISSUE THREAD

**Issue by cbloss** [Paul-DS/bootstrap-year-calendar#21]
Hey!

I'm trying to make it where I can pull events per a year instead of one call. I tried renderEnd which just causes an endless loop because I used the setDataSource (is there any other way to add events? I didn't see any in the documentation). customDataSourceRenderer works only on initial load. Is there a way to do it by year?

Thanks!

**Comment by Paul-DS** [comment]
I just update the widget to improve AJAX management.

Now you can use AJAX request to load your datasource when changing the current year, with the following code :

    var calendar = $('#calendar').calendar({
		yearChanged: function(e) {
			e.preventRendering = true;
			
			$(e.target).append('<div style="text-align:center"><img src="your-loading-image.gif" /></div>');
			
			$.ajax({ 
				url: "your-url", 
				success: function(dataSource) {  
					$(e.target).data('calendar').setDataSource(dataSource);
				} 
			});
		}
	});

Then, if you want to make your first loading using AJAX (if the data of the current year are not loaded with the page), just add the following line :

	calendar.setYear(new Date().getFullYear());

You should have something like this :

![ajax](https://cloud.githubusercontent.com/assets/15329946/15444482/904a4592-1ef1-11e6-8c0b-6bd4782e0c7e.gif)

**Comment by GaryGGG** [comment]
Paul,
I am new to this. Can you provide an example of server code (C# prefer) that generate the datasource?
Thanks!

**Comment by GaryGGG** [comment]
My code behind:
                    var dataSource = from b in bookings
                        select new 
                        {
                        id =  b.VillaID,
                        name = b.Actions.ToString(),
                        location = b.Notes,
                        startDate = b.CheckInDate.ToShortDateString(),
                        endDate = b.CheckOutDate.ToShortDateString()
                        };

                    var rows = dataSource.ToArray();
                    var retVal = Json(rows, JsonRequestBehavior.AllowGet);
                    return retVal;

**Comment by DarkSide666** [comment]
Event `yearChanged` is not mentioned in documentation: http://www.bootstrap-year-calendar.com/#Documentation/Events

**Comment by sergiodanilo** [comment]
`$(e.target).data('calendar').setDataSource(dataSource);` doesn't works!

**Comment by DarkSide666** [comment]
It should work.
Here is full, working example. I use it in my calendar: https://github.com/Paul-DS/bootstrap-year-calendar/issues/103

**Comment by robandwend** [comment]
With the current version not having the yearChanged event yet - I found I could get around it using the renderEnd event thus:

        renderEnd: function(e) {
            if (yearSave != e.currentYear) { getyear(e.currentYear); }
            yearSave = e.currentYear;
        },

If at the end of a render, the year has changed since the last render - then reload the next year.

My getyear function is below.  (I'm using twig to generate the page - hence the {{}}'s) Note that after getting the ajax data back, I have to correct the date formats, as the calendar requires 'date' format objects which can't be sent directly by ajax.

    function getyear(year)
    {
        $.ajax({ 
            url: "{{ path_for('trip.yearjson',{'year':''}) }}"+year, 
            success: function(dataSource) {  
                console.log("loaded source");
            var objs = JSON.parse(dataSource);  {# Convert to manageable format #}
            for (var i = 0; i < objs.length; i++)
            {
                objs[i].startDate = new Date(objs[i].startDate);
                objs[i].endDate = new Date(objs[i].endDate);
            }
            $('#calendar').data('calendar').setDataSource(objs);
            } 
        });

**Comment by William-H-M** [comment]
Hi, @robandwend if not wrong year changed it's include on this repo (not on actual release) you can check is mentioned on #139 if not wrong.

**Comment by Rajguru** [comment]
Hello @Paul-DS  , For me , this solution is working fine but yearChanged click event is in the latest release which i have referred from github project. But I am using npm installer for my project  for same but npm package repository does not have your latest changes. Can you please upload your latest changes to npm repository so that i can use that to get latest changes while running solution in any  environment. I am attaching screenshot for reference.  

Again Thanks for creation this solution. 
![calender-npm-repo](https://user-images.githubusercontent.com/7588677/35185753-24841814-fe2f-11e7-916d-04b5fbbdbcaf.png)

**Comment by delamux** [comment]
You should document de deprecated functions in the documentation.

the **renderEnd** function by **yearChanged** works fine.

thank you @robandwend .
